// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Infrastructure;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613171315_AddStudentIdToIssues")]
    partial class AddStudentIdToIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedToId")
                        .HasColumnType("bigint");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageObjectKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<long?>("ImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageStorageProvider")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("backend.Models.IssueCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWomenWelfare")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategory");

                    b.ToTable("IssueCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Electrical",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Plumbing",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Internet",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Furniture",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Cleaning",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Security",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Water Supply",
                            ParentCategory = "Infrastructure"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Room Maintenance",
                            ParentCategory = "Hostel"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Cleanliness",
                            ParentCategory = "Hostel"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Hostel Facilities",
                            ParentCategory = "Hostel"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Classroom Issue",
                            ParentCategory = "Academic"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Faculty Issue",
                            ParentCategory = "Academic"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Academic Facility Issue",
                            ParentCategory = "Academic"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Security Concern",
                            ParentCategory = "CampusSafety"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Unsafe Area",
                            ParentCategory = "CampusSafety"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Broken CCTV",
                            ParentCategory = "CampusSafety"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Poor Lighting",
                            ParentCategory = "CampusSafety"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Ragging",
                            ParentCategory = "StudentWelfare"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Bullying",
                            ParentCategory = "StudentWelfare"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Discrimination",
                            ParentCategory = "StudentWelfare"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Mental Wellbeing",
                            ParentCategory = "StudentWelfare"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            IsWomenWelfare = false,
                            Name = "Counseling Request",
                            ParentCategory = "StudentWelfare"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            IsWomenWelfare = true,
                            Name = "Harassment",
                            ParentCategory = "WomenWelfare"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            IsWomenWelfare = true,
                            Name = "Safety & Privacy Concern",
                            ParentCategory = "WomenWelfare"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            IsWomenWelfare = true,
                            Name = "Complaint Against Student",
                            ParentCategory = "WomenWelfare"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            IsWomenWelfare = true,
                            Name = "Complaint Against Faculty",
                            ParentCategory = "WomenWelfare"
                        });
                });

            modelBuilder.Entity("backend.Models.IssueTimeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueTimelines");
                });

            modelBuilder.Entity("backend.Models.IssueUpvote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("IssueId", "StudentId")
                        .IsUnique();

                    b.ToTable("IssueUpvotes");
                });

            modelBuilder.Entity("backend.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Issue", b =>
                {
                    b.HasOne("backend.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("backend.Models.IssueCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.IssueTimeline", b =>
                {
                    b.HasOne("backend.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("backend.Models.IssueUpvote", b =>
                {
                    b.HasOne("backend.Models.Issue", "Issue")
                        .WithMany("IssueUpvotes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.Issue", b =>
                {
                    b.Navigation("IssueUpvotes");
                });
#pragma warning restore 612, 618
        }
    }
}
